// @generated by `casparctl vms sync` — DO NOT EDIT BY HAND.
//
// This module is regenerated on every Caspar node build. It imports each VM
// plugin project enabled in the `vms/` folder and registers it with the
// caspar-vm-sdk plugin registry, so the node binary carries exactly the VM
// types the host admin selected — without the node source ever naming them.

use std::sync::Once;

static REGISTER: Once = Once::new();

/// Register every enabled VM plugin with the VMM plugin registry.
/// Idempotent — safe to call from multiple init paths.
pub fn register_all() {
    REGISTER.call_once(|| {
        caspar_vm_docker::register();
        caspar_vm_elpian::register();
        caspar_vm_elpify::register();
        caspar_vm_fire::register();
        caspar_vm_javascript::register();
        caspar_vm_modal::register();
        caspar_vm_wasm::register();
    });
}

/// The VM plugin keys compiled into this build.
pub fn enabled_vm_keys() -> Vec<&'static str> {
    vec![
        "docker",
        "elpian",
        "elpify",
        "fire",
        "javascript",
        "modal",
        "wasm",
    ]
}
